### ISSUE TITLE
Scale (or hide) range chart for mobile

### ISSUE THREAD

**Issue by MikePiper** [MikePiper/open-social-security#13]
relates to branch: component-for-range-of-options

Figuring out a way to scale the range chart for mobile would be good. Or maybe it would be easier/better to simply hide the component for mobile users. (Can mobile users even click on the table?)

**Comment by brian-courts** [comment]
How would I use my phone or tablet to run your current version (with range)?

**Comment by MikePiper** [comment]
Unfortunately I am not aware of any way to actually run the app on phone/tablet using locally installed code.

Chrome's Dev Tools has a way to simulate mobile devices. (On my version, I open javascript console, then there's a button in the top-left for "toggle device toolbar.")

Then you can choose different device sizes. And clicking fires "touch" events rather than "click" events.

I'm not really sure how realistic the whole thing is, but it's probably better than nothing.

And at least based on that, "touch" events *do* cause the range chart to respond (i.e., showing the output for the selected option) just like a click. So that's good.

But then there's still the issue of size. (Even if the chart itself fits on the screen, the output will be off-screen, so you have to scroll back and forth each time.) I'm leaning a little bit toward just hiding the whole thing on smaller devices, but definitely interested to hear your thoughts.

**Comment by brian-courts** [comment]
Dev Tools seems like a good option. I'll look into that. 
I've done very little development for mobile devices. How would we know that the program is on a mobile device? Size of screen? Could that be used as an ngif test in the HTML?
    On Saturday, May 16, 2020, 09:12:00 AM CDT, MikePiper <notifications@github.com> wrote:  
 
 


Unfortunately I am not aware of any way to actually run the app on phone/tablet using locally installed code.

Chrome's Dev Tools has a way to simulate mobile devices. (On my version, I open javascript console, then there's a button in the top-left for "toggle device toolbar.")

Then you can choose different device sizes. And clicking fires "touch" events rather than "click" events.

I'm not really sure how realistic the whole thing is, but it's probably better than nothing.

And at least based on that, "touch" events do cause the range chart to respond (i.e., showing the output for the selected option) just like a click. So that's good.

But then there's still the issue of size. (Even if the chart itself fits on the screen, the output will be off-screen, so you have to scroll back and forth each time.) I'm leaning a little bit toward just hiding the whole thing on smaller devices, but definitely interested to hear your thoughts.

**Comment by MikePiper** [comment]
ngif could be a way to do it.

I think it might be easier with css to set `display:none` when screen size is small.
https://www.w3schools.com/css/css3_mediaqueries_ex.asp

**Comment by MikePiper** [comment]
Just made a commit that uses css to hide the entire component when display size is small.
