### ISSUE TITLE
Convert range component output to unordered list and add ages

### ISSUE THREAD

**Issue by MikePiper** [MikePiper/open-social-security#14]
relates to branch: component-for-range-of-options

Maybe the "claim dates" part of the output would be a little more clear as an unordered list.

Also, I know from feedback I received on the original release of the calculator that people will want to see the age as well as the date.

Maybe something like this:

-----
**Selected option:**
- date1 (with age included)
- date2 (with age included)
- date3 (with age included)
- PV
- PV as percent of max
-----

**Comment by brian-courts** [comment]
Regarding the problems of which claim dates are reported, and how:

My system is very crude. I think what is needed is a variation of what you do when you show claim dates and ages for an alternative strategy - take the proposed dates and see which ones actually work, and derive the sentences you put in the output.

In fact, it might make sense to create that entire alternative strategy output, including the table of year-by-year benefits, when a person selects a date. I would put that in a separate <div> below the graph, rather than beside it (where my output is).

You're much more adept and familiar with those calcs, so if you'd like to take on that revision, I'd be delighted. 

If you want me to try, I'll give it a shot.

**Comment by MikePiper** [comment]
I can take this one on. Might not get to start working on it though until Monday or Tuesday. And I don't really have any sense of how hard it's going to be. We'll see!

**Comment by brian-courts** [comment]
I once thought a year-by-year table would be good for the selection, but I now think it would be best to just show the basic information, like the list you proposed.
It might be good to insert the selected option's claim dates into the Alternative Strategy at the bottom of the page, and show the table down there. A note beside the chart would direct the user's attention to that table. 
    On Saturday, May 16, 2020, 09:13:52 AM CDT, MikePiper <notifications@github.com> wrote:  
 
 


I can take this one on. Might not get to start working on it though until Monday or Tuesday. And I don't really have any sense of how hard it's going to be. We'll see!

**Comment by MikePiper** [comment]
I just made a new commit that uses the functions in solutionset.service to create strings related to the selected filling date(s), which are then used to populate an unordered list.

Would you mind giving it a test to see what you think? (I'll leave this "issue" open so that continued discussion can occur in case you have other suggestions/concerns/comments.)

I _think_ this also means we can also delete the various code relating to `selectedClaimDatesString` and `selectedPercentString`, but I wanted to check with you before doing so.
