### ISSUE TITLE
Error running presentvalue.service.spec.ts

### ISSUE THREAD

**Issue by brian-courts** [MikePiper/open-social-security#22]
Before making changes to files, when I ran
    ng test
I got 1 FAILED, 168 SUCCESS
In presentvalue.service.spec.ts, approximate line 1924, gives error:

Tests for maximizeCouplePViterateOnePerson should tell a divorced user with lower PIA, two children already entitled on ex-spouse record, and an assumed age at death of 75 to file at 62 and 1 month for retirement and child-in-care spousal benefits FAILED
        Expected $.year = 2020 to equal 2019.
        Expected $.month = 0 to equal 11.
        Error: Expected $.year = 2020 to equal 2019.
        Expected $.month = 0 to equal 11.

**Comment by MikePiper** [comment]
Thanks for catching this. At some point recently I added a "today" variable to BenefitService. I hadn't thought about it at the time, but that may cause some tests to fail over time as the month changes. The fix is easy at least -- just giving BenefitService.today the fake "today" date that matches PresentValueService.today for the test in question.
