### ISSUE TITLE
Ignored Saved Application for alternative claiming strategy

### ISSUE THREAD

**Issue by dave-sanders** [MikePiper/open-social-security#81]
The "Test an alternative claiming strategy:" near the bottom lets you test alternate claim dates. Entering claim dates up to six months in the past are rejected with error message [1] if the claim date is earlier than Full Retirement Age. However, I have a Saved Application on socialsecurity.gov with a start date less than six months ago BUT before my FRA. Once the Save Application is submitted, the start date on the app. is honored even if it's earlier than FRA. It would be nice if the optimizer would allow alternative claim dates up to six months ago regardless of FRA. If the date is before the FRA, the optimizer could warn "Retroactive applications are not allowed before FRA, but if you have a Saved App with this start date, that is okay."

[1] "The effective date for a retroactive application for retirement benefits must be no earlier than your full retirement age and no more than 6 months before today."

**Comment by dave-sanders** [comment]
Example:

Marital status: Single
Gender: Male
Date of birth: 12/15/1957   (thus FRA of 66 years, 6 months in 6/2024)
PIA: $1000 
Submit

Scroll to "Test an alternative claiming strategy" near the bottom.
Your month/year to claim retirement benefit::  3 2024.
Submit gives "The effective date for a retroactive application for retirement benefits must be no earlier than your full retirement age and no more than 6 months before today."

Yes, that is earlier than the 6/2024 FRA, but I have a saved application with claim date of 3/2024 on socialsecurity.gov. It would be nice if Submit showed strategy for up to 6 months prior but warned that an application for prior to FRA cannot be submitted unless previously started and saved.

Link for this example: 
https://opensocialsecurity.com/?additionalInput=false&&disabilityShow=false&&workingShow=false&&pensionShow=false&&mortalityShow=false&&childrenShow=false&&discountShow=false&&cutShow=false&&marital=single&&discount=2.09&&cutAssumption=false&&cutYear=2034&&cutPercent=23&&aGender=male&&aDOBm=12&&aDOBd=15&&aDOBy=1957&&aDisability=false&&aPIA=1000&&aFixedRBm=&&aFixedRBy=&&aWorking=false&&aQuitm=&&aQuity=&&aEarnings=0&&aFiled=false&&aFiledSurvivor=false&&aFixedSurvBm=&&aFixedSurvBy=&&aFiledMotherFather=false&&aFixedMFBm=&&aFixedMFBy=&&aEligiblePension=false&&aPensionm=1&&aPensiony=2020&&aGovPension=0&&aPIA2=1000&&aMortality=SSA2020&&aDeathAge=100&&bGender=female&&bDOBm=4&&bDOBd=15&&bDOBy=1960&&bDODm=4&&bDODy=2020&&bDisability=false&&bPIA=1000&&bFixedRBm=&&bFixedRBy=&&bWorking=false&&bQuitm=&&bQuity=&&bEarnings=0&&bFiled=false&&bEligiblePension=false&&bPensionm=1&&bPensiony=2020&&bGovPension=0&&bPIA2=1000&&bMortality=SSA2020&&bDeathAge=100&&children=false&&numberOfChildren=0

**Comment by dave-sanders** [comment]
Withdrawing issue since it might be considered a feature request.

**Comment by dave-sanders** [comment]
Withdrawing

**Comment by MikePiper** [comment]
@dave-sanders Thank you for providing your input. Sorry for being slow to reply to this. I've been traveling and have mostly only been able to keep up with time-sensitive things.

You are correct that in certain cases, if a person has already established a "protective filing date" as discussed in HI 03010.020, then they are allowed to file as of that date.

https://secure.ssa.gov/poms.nsf/lnx/0603010020

This is one simplification that I intentionally chose to implement, because of the infrequency with which the concept applies applies, relative to (in my opinion) the complexity introduced by trying to explain it on the page. I do understand though that other people may have very reasonably chosen to go a different route.

At this point, given how deeply the "earliest possible filing date" is baked into various calculations, choosing to change that functionality would be a major project.
